# Generated by Django 5.2.6 on 2025-09-21 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('sat_5pm', 'Saturday 5 PM'), ('sun_9am', 'Sunday 9 AM'), ('sun_11am', 'Sunday 11 AM'), ('sun_6pm', 'Sunday 6 PM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_team', models.CharField(blank=True, choices=[('wf', 'wake forest'), ('unc', 'north carolina'), ('fau', 'flordia atlantic'), ('wvu', 'west virgina'), ('uf', 'flordia')], max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
